name: Test release build
run-name: ${{ github.actor }} Testing exe Build
on:
  workflow_dispatch:
env:
  MY_API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
  VERSION_TAG: ${{ github.GITHUB_REF_NAME }}
jobs:
  minify_code:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: minifying
      uses: nizarmah/auto-minify@v2.1
      with:
        overwrite: true
        js_engine : 'uglify-js'
    - name: removing git folder (to keep space down in exe)
      run: |
          ls -la
          rm -fr .git/*
          rmdir .git
          ls -la
    - name: uploading artifact
      uses: actions/upload-artifact@v3
      with:
        name: mini-artifacts
        path: .      
  creating_exe:
    runs-on: windows-latest    
    needs: minify_code
    steps:
    - name: importing artecfact
      uses: actions/download-artifact@v3
      with:
        name: mini-artifacts
    - uses: actions/setup-node@v3
      with:
        node-version: '18.6.0'
    - name: Create Version.txt
      run: |
          echo v0.0.0 > SoftwareVersion.txt
    - name: Creating exe
      run: |
          cat extensions/chatbot/chatbot.js
          npm i -D caxa
          npm install
          npx caxa -m "Unpacking " -i . -o StreamRoller.exe -- "{{caxa}}/install.cmd" "{{caxa}}"
    - name: Create Release.txt
      run: |
          echo Release version ${{ github.ref_name }} >> Release.txt
    - name: Zip up exe
      run: |
        7z a StreamRoller.zip StreamRoller.exe
    - name: uploading artifact
      uses: actions/upload-artifact@v3
      with:
        name: StreamRoller.zip
        path: StreamRoller.exe
